export const API_ROUTES = {
	// CATEGORY
	GET_CATEGORIES: `/api/posts`,
	CREATE_CATEGORY: "",
	UPDATE_CATEGORY: "",
	DELETE_CATEGORY: "",
	// COURSE
	GET_COURSES: "",
	CREATE_COURSE: "",
	UPDATE_COURSE: "",
	DELETE_COURSE: "",
	// COUPON
	GET_COUPONS: "",
	CREATE_COUPON: "",
	UPDATE_COUPON: "",
	DELETE_COUPON: "",
	// PAYMENTS
	GET_PAYMENTS: "",
	CREATE_PAYMENT: "",
	UPDATE_PAYMENT: "",
	DELETE_PAYMENT: "",
}
